### ISSUE TITLE
Can Telephoto zooming library be easily integrated with landscapist?

### ISSUE THREAD

**Issue by CyrilNb** [skydoves/landscapist#293]
This new library from CashApp developer has just been released.

It's about zoomable image in Compose.

I can be easily implemented by ditching AsyncImage for this.

Can it be easily integrated into landscapist (it is already by default?)

https://saket.github.io/telephoto/

**Comment by skydoves** [comment]
@CyrilNb I was planning to implement a dedicated zoomable [ImagePlugin](https://github.com/skydoves/landscapist#imagecomponent-and-imageplugin) for this, and still on my mind when I have a moment. (Recently, I couldn't work on this much due to lack of my time 😓 )

Like the sample below, I just tested the telephoto library with Landscapist in the demo project, and it works well.

```kotlin
  GlideImage(
    imageModel = { poster.image },
    modifier = Modifier
      .aspectRatio(0.8f)
      .zoomable(rememberZoomableState()),
  ..
```

But basically, these two libraries focus on a different solution. Landscapist focuses on loading the basic images with a combination of many plugins so that you can use many add-ons easily, such as animations, placeholder, blur transformation, and so on. On the other hand, Telephoto's primary feature seems to focus on zoomable like [PhotoView](https://github.com/Baseflow/PhotoView). 

At this point, maybe I can consider using the telephoto library to implement a zoomable image plugin, but not sure if it's worth making it an independent plugin because it seems to be easy to use by itself by adding `.zoomable(rememberZoomableState()` on your Modifier.

@saket, what do you think? 😄 Maybe we can also find any collaboration points.

**Comment by saket** [comment]
👋 Hi @skydoves! I was initially planning to add support for Glide through landscapist until I learned that Glide is already working on an [official compose implementation](https://bumptech.github.io/glide/int/compose.html). It is not as stable as landscapist yet, but I figured it'll be future proof. 

> but not sure if it's worth making it an independent plugin because it seems to be easy to use by itself by adding .zoomable(rememberZoomableState() on your Modifier.

It is actually slightly more involved because you'll also need to enable [edge detection](https://saket.github.io/telephoto/zoomable/#edge-detection) of images and [sub-sampling](https://saket.github.io/telephoto/zoomableimage/sub-sampling/) for bitmaps. Edge detection will be straightforward but sub-sampling may not be, especially if you want to support placeholders and crossfade transitions.

Alternatively, could landscapist offer `Zoomable*Image()` [extensions](https://saket.github.io/telephoto/zoomableimage/custom-image-loaders/)?

**Comment by skydoves** [comment]
Hi @saket 👋, I appreciate your quick response and the history!

Sounds like a plan! I will take a look into the details of enabling [edge detection](https://saket.github.io/telephoto/zoomable/#edge-detection) of images and [sub-sampling](https://saket.github.io/telephoto/zoomableimage/sub-sampling/) for bitmaps. Zoomable*Image() [extensions](https://saket.github.io/telephoto/zoomableimage/custom-image-loaders/) also sounds great, but I'm not sure if it will be compatible with the [image plugin](https://github.com/skydoves/landscapist#imagecomponent-and-imageplugin).

I can make a PR about the skeleton of the zoomable image plugin using Telephoto and get back to you in early June when I have a moment. Or if you're interested in being a new primary co-maintainer of landscapist, I'd be very happy to walk you through the project and collaboration! 😄

**Comment by skydoves** [comment]
The priority of this feature was changed, so let me re-open this issue when I have a moment.
