### ISSUE TITLE
rememberUpdatedState required to make it work properly inside Pager.

### ISSUE THREAD

**Issue by drpbprateek** [skydoves/landscapist#301]
**Please complete the following information:**
- Library Version [e.g. v2.1.9]
 
When using GlideImage inside Pager each has its own ViewModel, so there is some delay in loading the data like image URL:-

For ex:-

```

//From Glide Official Compose Library
GlideImage(model = state.imageUrl,
contentDescription = "",
contentScale = ContentScale.FillWidth)
Spacer(modifier = Modifier.height(8.dp))

//From landscapist
GlideImage(
modifier = Modifier.fillMaxWidth(),
imageModel = { state.imageUrl },
imageOptions = ImageOptions(contentScale = ContentScale.FillWidth) )
```

The first implementation always works but the 2nd implementation because it is expecting the URL as a lambda, is hit and miss and the fix is to use rememberUpdatedState.

Is my understanding correct? Should it be added in Usages Doc?

**Comment by skydoves** [comment]
@drpbprateek Hmm, this is interesting. So you're meaning the image URL will be provided lately by your ViewModel, and Landscapist doesn't load it correctly?

**Comment by skydoves** [comment]
I'm wondering if it works well if you give the `contentDescription` on your ImageOptions like the example below:

```kotlin
mageOptions = ImageOptions(contentScale = ContentScale.FillWidth, contentDescription = state.imageUrl)
```

**Comment by skydoves** [comment]
Landscapist `2.2.2` has been released. Would you try to build with this?

**Comment by drpbprateek** [comment]
Ading contentDescription didn't help but ignore rememberUpdatedState , even if i move the URL out like this it work.

```
val newUrl = mcqData.imageUrl
GlideImage(
modifier = Modifier.fillMaxWidth(),
imageModel = { newUrl },
imageOptions = ImageOptions(contentScale = ContentScale.FillWidth, contentDescription = "")
 )
```

Let me try 2.2.2 and i will update here

**Comment by drpbprateek** [comment]
2.2.2 Issue is fixed.
Thanks for the support @skydoves. I still would like to know why this was happening.

**Comment by skydoves** [comment]
As I mention to you in the previous comment, the recomposition rule is very strict in landscapist. So even if you try to recompose the entire composable that includes Landscapist, the actual image request will not be recomposed easily. The only issue here is after releasing the bitmap resource from the Glide. If Landscapist releases the bitmap resources, we can't reuse the same references with Glide, which does not allow them to be recomposed. This used to make your images is not be loading correctly sometimes.

Anyway, good to hear that. I'm closing this issue since it was fixed. Thanks!
